In [1]:
# import the required libraries
import pandas as pd
import numpy as np

In [2]:
# read in the file 
hotel_bookings = pd.read_csv('hotel_bookings.csv')
hotel_bookings.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [4]:
# Find the percentage of missing values in each column
hotel_bookings.isnull().sum()*100/len(hotel_bookings)

hotel                              0.000000
is_canceled                        0.000000
lead_time                          0.000000
arrival_date_year                  0.000000
arrival_date_month                 0.000000
arrival_date_week_number           0.000000
arrival_date_day_of_month          0.000000
stays_in_weekend_nights            0.000000
stays_in_week_nights               0.000000
adults                             0.000000
children                           0.003350
babies                             0.000000
meal                               0.000000
country                            0.408744
market_segment                     0.000000
distribution_channel               0.000000
is_repeated_guest                  0.000000
previous_cancellations             0.000000
previous_bookings_not_canceled     0.000000
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
agent                             13.686238
company                           94.306893
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
reservation_status_date            0.000000
dtype: float64

In [5]:
# Deal with the missing values 
hotel_bookings = hotel_bookings.drop('company',axis=1)

hotel_bookings.loc[hotel_bookings['children'].isnull()]['children']
hotel_bookings['children'] = hotel_bookings['children'].replace(np.nan,-1)
hotel_bookings['country'] = hotel_bookings['country'].replace(np.nan,'Unknown')
mean = hotel_bookings['agent'].mean()
hotel_bookings['agent'] = hotel_bookings['agent'].replace(np.nan,mean)

In [6]:
# Rename columns 
hotel_bookings.rename(columns = {'adults' : 'num_adults','children' : 'num_children','babies' : 'num_babies'},inplace=True)
hotel_bookings.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'num_adults', 'num_children', 'num_babies',
       'meal', 'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='str')

In [7]:
# Correct data types
hotel_bookings.dtypes
hotel_bookings = hotel_bookings.astype({'num_children' : 'int','is_repeated_guest': 'boolean','is_canceled' : 'boolean'})
hotel_bookings.dtypes

hotel                                 str
is_canceled                       boolean
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                    str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
num_adults                          int64
num_children                        int64
num_babies                          int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                 boolean
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                             float64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

In [8]:
# Create bins
hotel_bookings['lead_time'].unique()
bins = [0,100,200,300,400,500,600,700,800]
labels = ['0-100','101-200','201-300','301-400','401-500','501-600','601-700','701-800']
hotel_bookings['lead_time_binned'] = pd.cut(hotel_bookings['lead_time'],bins=bins,labels=labels)
hotel_bookings[['lead_time','lead_time_binned']]

        lead_time lead_time_binned
0             342          301-400
1             737          701-800
2               7            0-100
3              13            0-100
4              14            0-100
...           ...              ...
119385         23            0-100
119386        102          101-200
119387         34            0-100
119388        109          101-200
119389        205          201-300

[119390 rows x 2 columns]

In [9]:
# Handle duplicates in the data
hotel_bookings.loc[hotel_bookings.duplicated(keep=False)]
hotel_bookings = hotel_bookings.drop_duplicates(keep='last')
hotel_bookings.shape

(87389, 32)